// Command gen-chroma-css regenerates the static CSS assets the Wails frontend
// links, so they are not rebuilt on every render (MD-WAILS DR-4).
//
// It writes two files into frontend/dist/:
//   - chroma.css : dual-theme Chroma syntax-highlighting CSS (github + dracula)
//   - ui.css     : md-view in-page UI chrome (frontmatter block, copy/reMarkable/
//     toolbar buttons, code-block copy button) + dark overrides
//
// Usage:  make frontend-css     (or:  go run ./cmd/gen-chroma-css)
package main

import (
	"fmt"
	"os"

	"github.com/go-go-golems/md-view/pkg/renderer"
)

func main() {
	if err := os.MkdirAll("frontend/dist", 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "cannot create frontend/dist: %v\n", err)
		os.Exit(1)
	}

	chromaCSS, err := renderer.ChromaCSSBoth()
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot generate chroma css: %v\n", err)
		os.Exit(1)
	}
	writeFile("frontend/dist/chroma.css",
		"/* AUTO-GENERATED by `make frontend-css` (cmd/gen-chroma-css). DO NOT EDIT. */\n"+
			"/* Dual-theme Chroma syntax-highlighting CSS: github (light) + dracula (dark). */\n"+
			chromaCSS)

	writeFile("frontend/dist/ui.css",
		"/* AUTO-GENERATED by `make frontend-css` (cmd/gen-chroma-css). DO NOT EDIT. */\n"+
			"/* md-view in-page UI chrome (frontmatter, buttons) + dark overrides. */\n"+
			renderer.UICSS())

	fmt.Println("generated frontend/dist/chroma.css and frontend/dist/ui.css")
}

func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "cannot write %s: %v\n", path, err)
		os.Exit(1)
	}
}
